

create tables
PREFIX MT_

user


CREATE TABLE IF NOT EXIST `MT_USERS` (
    `id`    INTEGER PRIMARY KEY AUTOINCREMENT,
    `name`  TEXT,
    `apellido1` TEXT,
    `apellido2` TEXT,
    `email` TEXT NOT NULL UNIQUE,
    `password`  TEXT,
    `image` INTEGER,
    `direction` TEXT,
    `city`  TEXT,
    `state` TEXT,
    `country`   TEXT,
    `created_at`    TEXT DEFAULT '0000:00:00 00:00:00',
    `updated_at`    TEXT DEFAULT '0000:00:00 00:00:00',
    `DELETED`   INTEGER DEFAULT 0
);



mantenimiento


CREATE TABLE IF NOT EXIST `MT_MANTENIMIENTOS` (
    `ID`    INTEGER PRIMARY KEY AUTOINCREMENT,
    `AUTO`  INTEGER NOT NULL,
    `TYPE`  INTEGER,
    `USER`  INTEGER,
    `TALLER`    INTEGER,
    `PRECIO`    NUMERIC,
    `MONEDA`    TEXT,
    `CREATED_AT`    TEXT DEFAULT '0000:00:00 00:00:00',
    `UPDATED_AT`    TEXT DEFAULT '0000:00:00 00:00:00',
    `DELETED`   INTEGER DEFAULT 0,
    FOREIGN KEY(`AUTO`) REFERENCES MT_AUTO(ID),
    FOREIGN KEY(`USER`) REFERENCES `MT_USER`(`ID`)
    FOREIGN KEY(`TALLER`) REFERENCES `MT_TALLERES`(`ID`)
);


FLUIDOS

CREATE TABLE TABLE IF NOT EXIST `MT_FLUIDOS` (
    `ID`    INTEGER PRIMARY KEY AUTOINCREMENT,
    `ID_MANTENIMIENTO`  INTEGER NOT NULL,
    `ACEITE`    INTEGER DEFAULT NULL,
    `DIRECCION` INTEGER DEFAULT NULL,
    `REFRIGERACION` INTEGER DEFAULT NULL,
    `VALVULINA` INTEGER DEFAULT NULL,
    `FILTRO_ACEITE` INTEGER DEFAULT NULL,
    `FILTRO_COMBUSTIBLE`    INTEGER DEFAULT NULL,
    `FILTRO_HABITACULO` INTEGER DEFAULT NULL,
    `FILTRO_DIRECCION`  INTEGER DEFAULT NULL,
    `CREATED_AT`    TEXT DEFAULT '0000:00:00 00:00:00',
    `UPDATED_AT`    TEXT DEFAULT '0000:00:00 00:00:00',
    `DELETED`   INTEGER DEFAULT 0,
    FOREIGN KEY(`ID_MANTENIMIENTO`) REFERENCES `MT_MANTENIMIENTO`(`ID`)
);



AUTO


CREATE TABLE TABLE IF NOT EXIST `MT_AUTOS` (
    `ID`    INTEGER PRIMARY KEY AUTOINCREMENT,
    `MATRICULA` TEXT,
    `MARCA` TEXT,
    `MODELO`    TEXT,
    `BASTIDOR`  TEXT,
    `COMBUSTIBLE`   TEXT,
    `KM`    INTEGER,
    `FECHA_FABRICACION` TEXT DEFAULT '0000:00:00 00:00:00',
    `FECHA_COMPRA`  TEXT DEFAULT '0000:00:00 00:00:00',
    `USUARIO_HABITUAL`  INTEGER,
    `IMAGE` INTEGER,
    `CREATED_AT`    TEXT DEFAULT '0000:00:00 00:00:00',
    `UPDATE_AT` TEXT DEFAULT '0000:00:00 00:00:00',
    `DELETED`   INTEGER DEFAULT 0,
    FOREIGN KEY(`USUARIO_HABITUAL`) REFERENCES MT_USERS(ID)
);



TALLERES


CREATE TABLE IF NOT EXIST `MT_TALLERES` (
  `ID`  INTEGER PRIMARY KEY AUTOINCREMENT,
  `NOMBRE`  TEXT,
  `DIRECCION` TEXT,
  `CITY`  TEXT,
  `STATE` TEXT,
  `COUNTRY` TEXT,
  `IMAGE` INTEGER,
  `EMAIL` TEXT,
  `PHONE` TEXT,
  `WEB` TEXT,
  `GMAPS` TEXT,
  `CALIFICACION`  NUMERIC,
  `CREATED_AT`  TEXT DEFAULT '0000:00:00 00:00:00',
  `UPDATED_AT`  TEXT DEFAULT '0000:00:00 00:00:00',
  `DELETED` INTEGER DEFAULT 0
);
